---
title: "PERMANOVA"
author: "Christian Ayala"
output: html_document
editor_options: 
  chunk_output_type: console
---

# 1. Load libraries

```{r}
suppressWarnings(suppressMessages(library(tidyverse)))
suppressWarnings(suppressMessages(library(RColorBrewer)))
suppressWarnings(suppressMessages(library(vegan)))
```

# 2. Import data

```{r}
# Import data

# Feature_correspondence
features <- read.csv("../../tables/featureCorrespondence_MS2_e4.csv", row.names = 1)
features <- as.data.frame(t(features))
# distance matrix - bray
dm <- vegdist(features, method="bray")

# Metadata
metadata <- read.csv("../../tables/metadata_bog.csv")
metadata$SampleCode <- gsub("-", '.', metadata$SampleCode, fixed = T)
```

# 3. PERMANOVA

Permutational Multivariate Analysis of Variance Using Distance Matrices
?adonis

Sources: https://rdrr.io/rforge/vegan/man/adonis.html, https://rpubs.com/collnell/manova

```{r}
set.seed(456)
permanova <- adonis(dm ~ Sample_type + Time, 
                    data=metadata, 
                    permutations=999, 
                    method="bray")
permanova
# no reps in this example, so no significance...
filename <- file.path('..', '..', 'tables', 'permanova_e4.csv')
write.csv(as.data.frame(permanova$aov.tab), filename)
```

Which taxa/feature contribute most to the community differences?

https://mibwurrepo.github.io/Microbial-bioinformatics-introductory-course-Material-2018/multivariate-comparisons-of-microbial-community-composition.html

```{r}

set.seed(456)
sub_metadata <- metadata %>% 
  filter(Sample_type != 'peat')
sub_features <- features[rownames(features) %in% sub_metadata$SampleCode,]
# LEAFLIFE; adonis tests homogeneity of dispersion among groups
per.contrib <- adonis(sub_features ~ Sample_type, data=sub_metadata, permutations=999, method="bray")
per.contrib
```

Pairwise comparisons for feature contribution, did not find any *significative* differences among the groups.

```{r}
# ## Interpretation:
# # The R-square value is the important statistic for interpreting Adonis as it gives you the effect size. For example an R-squared of 0.44 means that 44% of the variation in distances is explained by the grouping being tested. The p value tells you whether or not this result was likely a result of chance. A p value of 0.05 means that there is a 5% chance that you detected a difference between groups (however large or small) when indeed there was none (the null hypothesis). 
# 
# ############# extract coefficients for Feature representation
# # to get coefficients supply the features df instead of the matrix dm
# # matrix of coefficients of the linear model, with rows representing sources of variation and columns representing species; each column represents a fit of a species abundance to the linear model. These are what you get when you fit one species to your predictors.
# per.contrib.features <- coefficients(per.contrib)['Treatment1',]
# per.contrib.features <- per.contrib.features[rev(order(abs(per.contrib.features )))]
# per.contrib.features <- as.data.frame(per.contrib.features) 
# colnames(per.contrib.features) <- paste0(test, 'f.contrib')
# per.contrib.features <- signif(per.contrib.features, 2)
# per.contrib.features$Features <- rownames(per.contrib.features)
# # filename <- paste0("features_contribution_Treatment.csv")
# # write.csv(per.contrib.features, filename)
```


<!-- NEGATIVE == DRIVING INOCULUM -->
<!-- POSITIVE == DRIVING CONTROL -->

<!-- # 4. Feature Contribution -->

```{r}
# t2 = quantile(abs(per.contrib.features$Trt.f.contrib), 0.60)
# t2
#
# per.contrib.features.g <- mutate(per.contrib.features,
#                             Group = if_else(abs(Trt.f.contrib)<t2, 'low contribution',
#                                                 if_else(Trt.f.contrib>t2, 'Control', 'Inoculum')))
#
# write.csv(per.contrib.features.g, "features_contribution_Group_Treatment.csv", row.names = F)
#
# trt.contrib <-
#   per.contrib.features.g %>%
#   filter(abs(Trt.f.contrib)>t2) %>%
#   ggplot(aes(x = reorder(Features, Trt.f.contrib), y = Trt.f.contrib, fill = Trt.f.contrib > 0)) +
#     geom_bar(stat="identity", width = 1, color='black', size=0.1, alpha=0.6) +
#     ylab("Contribution") +
#     xlab("MS Features") +
#     ggtitle(paste0("Contribution of features to Treatment")) +
#     scale_fill_manual(values = c('#117733', '#AA3377'), labels = c('Inoculum', 'Control')) +
#     # geom_hline(yintercept = t2, color = '#AA3377', size=0.5) +
#     # geom_hline(yintercept = - t2, color = '#117733', size=0.5) +
#     # scale_color_manual(values = list_of_colors) +
#     # coord_flip() +
#     theme_linedraw(base_size = 8) +
#     theme(
#       legend.title = element_blank(),
#       legend.position = "top",
#       legend.key.size = unit(0.3, 'cm'),
#         # axis.text.y = element_blank(),
#         # axis.ticks.y = element_blank(),
#         panel.grid.major.x = element_blank(),
#         # panel.grid.minor.x = element_blank(),
#         axis.text.x = element_blank(),
#         axis.ticks.x = element_blank()
#     )
#
# trt.contrib
# ggsave('Ft_Contribution_barplot.png',units=c('in'), width=6, height=4, dpi=300, trt.contrib)
```




```{r}
# # total features
# nfeatures = dim(per.contrib.features.g)[1]
# 
# # annotations
# ctrl <- per.contrib.features.g %>% filter(Trt.f.contrib > t2)
# n.ctrl <- dim(ctrl)[1]
# 
# inoc <- per.contrib.features.g %>% filter(Trt.f.contrib < -t2)
# n.inoc <- dim(inoc)[1]

# total <- paste0(nfeatures,' features detected in total.')
# upfeatures <- paste0(n.ctrl,' driving Brevideciduous.')
# downfeatures <- paste0(n.inoc,' driving Deciduous.')
# 
# total; upfeatures; downfeatures

# ft_count <- per.contrib.features.g %>% 
#   group_by(Group) %>% 
#   count()

# n.f.ctrl <- pull(ft_count[ft_count$Group=='Control', "n"])
# n.f.inoc <- pull(ft_count[ft_count$Group=='Inoculum', "n"])
```

