---
title: "Data import - Metabotandem"
author: "Christian Ayala"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

# 1. Importing libraries

Make sure `xcms` is installed.

```{r}
library(xcms)
doParallel::registerDoParallel(10)
```

# 2. Import data

**Important** Data was already in centroid mode.

```{r}

setwd('/groups/tfaily/cayalaortiz/bog_metabolomics/')
# define metadata, ie, phenotypic data
<<<<<<< HEAD
pd <- read.csv("/tables/metadata_bog.csv")

# get filenames from directory
files <- file.path('data', pd$FileName)
=======
pd <- read.csv("../tables/metadata_bog.csv")

# get filenames from directory
files <- file.path('..', 'data', pd$FileName)
>>>>>>> 0a2dda5ad1cac3890fb0b037db38fc867cb831d8

# Read the data:
data_cent <- readMSData(files, 
                        pdata = new("NAnnotatedDataFrame", pd), 
                        mode = "onDisk",
                        verbose = TRUE)
```

The MS experiment is now represented as an `OnDiskMSnExp` object. 

Information stored in the `OnDiskMSnExp` object after import:
```{r}
show(data_cent)
```

Check if data is centroided:

```{r}
prelim <- fData(data_cent)[1:100,]
unique(fData(data_cent)$centroided)
```

# 3. Save R object as `.RData`

Save as an R object so later, you don't need to re-import the data
```{r}
## Save data object as rds
<<<<<<< HEAD
save_file <- file.path('data', 'data_centroided.RData')
=======
save_file <- file.path('..', 'data', 'data_centroided.RData')
>>>>>>> 0a2dda5ad1cac3890fb0b037db38fc867cb831d8
save(data_cent, pd, files, file = save_file)
```

